name: "botAI"

data_loader:
  data_path: "./data/dataset.pgn"
  n_games: 10
  n_workers: 0

setup_args:
  wandblog : True
  wandb_name: null
  resume: false   # checkpoint path (if true, set path in resume_path)
  resume_path: null
  device: "cuda"   # if gpu, set a value in n_gpu
  n_gpu: null
  logger: ['logfile', 'stdout']

exp_args:
  type_exp: "train"   #type of experiment (train, test)
  batch_size: 64
  lr: 0.06    # learning rate
  epoch: 100
  eval_step: 10   # rate of evaluation step
  optimizer: "sgd"  # optimizer (sgd, adam)
  loss: "cross_ent"   # loss (mse, cross_ent)
  weight_decay: 10
  dropout: 0.5
  scheduler: "exp"
  seed: 10


encoder:
  in_channel_dim: 1 # channels of the input
  input_dim: 67    # input dimension of encoder
  latent_dim: 32   # dimension of encoded features
  type: "conv"   # (linear, conv)

decoder:
  output_dim: 4184 # output dimension of action space
  type: "linear"   # (linear)
